(function(){var d=void 0,g=true,h=null,j=false;function k(){return function(){}}function l(a){return function(){return this[a]}}function m(a){return function(){return a}}var n,p=this;
function aa(a){var b=typeof a;if(b=="object")if(a){if(a instanceof Array)return"array";else if(a instanceof Object)return b;var c=Object.prototype.toString.call(a);if(c=="[object Window]")return"object";if(c=="[object Array]"||typeof a.length=="number"&&typeof a.splice!="undefined"&&typeof a.propertyIsEnumerable!="undefined"&&!a.propertyIsEnumerable("splice"))return"array";if(c=="[object Function]"||typeof a.call!="undefined"&&typeof a.propertyIsEnumerable!="undefined"&&!a.propertyIsEnumerable("call"))return"function"}else return"null";
else if(b=="function"&&typeof a.call=="undefined")return"object";return b}function ca(a,b,c){return a.call.apply(a.bind,arguments)}function da(a,b,c){if(!a)throw Error();if(arguments.length>2){var e=Array.prototype.slice.call(arguments,2);return function(){var c=Array.prototype.slice.call(arguments);Array.prototype.unshift.apply(c,e);return a.apply(b,c)}}else return function(){return a.apply(b,arguments)}}
function r(a,b,c){r=Function.prototype.bind&&Function.prototype.bind.toString().indexOf("native code")!=-1?ca:da;return r.apply(h,arguments)}function ea(a,b){function c(){}c.prototype=b.prototype;a.ma=b.prototype;a.prototype=new c;a.prototype.constructor=a};var ga={scroll:5E3,keydown:5E3,mousemove:5E3,resize:5E3,mousedown:5E3,focus:5E3,pageload:5E3},ha={scroll:2E4,keydown:5E3,mousemove:5E3,resize:5E3,mousedown:5E3,focus:5E3,pageload:5E3};function ka(){for(var a="",b=0;b<16;b++)a+=Math.random();return a}function la(a,b){var c="",e=ma(encodeURIComponent(a));e.splice(b||5,e.length);s(e,function(a){if(a==0)a="A";else{a>>>=0;for(var b="",e;a>0;)e=a%64,b="ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789_-".charAt(e)+b,a>>>=6;a=b}c+=a});return c}
function ma(a){a+=String.fromCharCode(128);for(var b=[1518500249,1859775393,2400959708,3395469782],c=1732584193,e=4023233417,f=2562383102,i=271733878,q=3285377520,B=[],o,C,M,P,S,fa=Math.ceil((a.length/4+2)/16),ba=[fa],N=0,E;N<fa;N++){ba[N]=[];for(o=0;o<16;o++)ba[N][o]=a.charCodeAt(N*64+o*4)<<24|a.charCodeAt(N*64+o*4+1)<<16|a.charCodeAt(N*64+o*4+2)<<8|a.charCodeAt(N*64+o*4+3)}N=(a.length-1)*8;a=fa-1;ba[a][14]=Math.floor(N/Math.pow(2,32));ba[a][15]=N&4294967295;for(N=0;N<fa;N++){for(E=0;E<16;E++)B[E]=
ba[N][E];for(E=16;E<80;E++)B[E]=(B[E-3]^B[E-8]^B[E-14]^B[E-16])<<1|(B[E-3]^B[E-8]^B[E-14]^B[E-16])>>>31;a=c;o=e;C=f;M=i;P=q;for(E=0;E<80;E++)S=Math.floor(E/20),S=(a<<5|a>>>27)+(S==0?o&C^~o&M:S==1?o^C^M:S==2?o&C^o&M^C&M:o^C^M)+P+b[S]+B[E]&4294967295,P=M,M=C,C=o<<30|o>>>2,o=a,a=S;c=c+a&4294967295;e=e+o&4294967295;f=f+C&4294967295;i=i+M&4294967295;q=q+P&4294967295}return[c,e,f,i,q]}
function na(a){var b=p.navigator,c=p.window.screen,e=[b.userAgent,b.platform,(new Date).getTimezoneOffset(),c.width+c.height+c.colorDepth];s(b.plugins,function(a){e.push(a.name+a.description+a.filename+a[0].type)});b=p.performance;e=e.concat([b&&b.now?b.now():"",document.title,p.location.href,t(),ka()]);return e.concat(a||[]).join()}function u(a,b,c){var e=Array.prototype.slice,f=e.call(arguments,2);return function(){return a.apply(b,f.concat(e.call(arguments)))}}
function v(a){return typeof a!=="undefined"}function oa(a){return a.replace(/^www\./,"")}function w(a,b,c,e){a.addEventListener?a.addEventListener(b,c,!!e):a.attachEvent&&a.attachEvent("on"+b,c)}function pa(a,b,c){a.removeEventListener?a.removeEventListener(b,c,j):a.detachEvent&&a.detachEvent("on"+b,c)}function qa(a){return typeof a==="number"}function sa(a){return typeof a==="string"}function ta(a){return typeof a==="function"}
function ua(a){a=new Date(+a);return Date.UTC(a.getFullYear(),a.getMonth(),a.getDate())}function t(){return(new Date).getTime()}function va(a){return encodeURIComponent(a)}function s(a,b){if((!!a&&a.constructor===Object)===g)for(var c in a){if(a.hasOwnProperty(c)&&b(a[c],c)===j)break}else{c=0;for(var e=a.length;c<e;c++)if(b(a[c],c)===j)break}}function wa(a,b){for(var c=0,e=a.length;c<e;c++)if(b(a[c]))return c;return-1}function xa(a){var b=p.pSUPERFLY_video,a=wa(b,a);if(a>-1)return b[a]}
function ya(a){return a===d?0:t()-a}function za(a,b){var c,e,f="c"+Math.round(Math.random()*1E9);e=250;a+=(a.indexOf("?")>-1?"&":"?")+(c||"callback")+"=_cb_call."+f;c=document.createElement("script");var i=Aa(f,c);c.id=f;c.type="text/javascript";c.charset="UTF-8";c.src=a;var q=document.getElementsByTagName("head");if(q=q&&q[0]){var B=p._cb_call||(p._cb_call={});e=setTimeout(Ba(b,i),e);B[f]=Ca(b,i,e);q.appendChild(c)}}function Ba(a,b){return function(){b();a(d,"TIMEOUT")}}
function Ca(a,b,c){return function(e){b(c);a(e)}}function Aa(a,b){return function(c){c&&clearTimeout(c);setTimeout(function(){b&&b.parentNode&&b.parentNode.removeChild(b)},0);var e=p._cb_call,f=j;if(e&&(c?delete e[a]:e[a]=Da,s(e,function(){f=g;return j}),!f))try{delete p._cb_call}catch(i){p._cb_call=d}}}function Da(){}
function Ea(a,b){if(a===b)return 0;if(a.length===0)return b.length;if(b.length===0)return a.length;for(var c=[],e=0,f=b.length;e<=f;e++)c[e]=[e];for(var i=0,q=a.length;i<=q;i++)c[0][i]=i;for(var B,o,C,e=1;e<=f;e++)for(i=1;i<=q;i++)B=e-1,o=i-1,C=c[B][o],b.charAt(B)==a.charAt(o)?c[e][i]=C:(o=c[e][o]+1,B=c[B][i]+1,C+=2,c[e][i]=Math.min(o,B,C));return c[b.length][a.length]}function Fa(a){return a===d?0:t()-a}function x(a){return Math.round(a===-1||isNaN(a)?-1:a*1E3)}
var Ga,Ha=p.setInterval,Ia=p.clearInterval,Ja=p.setTimeout,Ka=p.clearTimeout;function La(a){switch(a){case d:return"undefined";case "":return"empty";default:return a}}function Ma(a){switch(a){case "undefined":break;case "empty":return"";default:return a}};function Na(a,b){var c,b=b||"*";c=c||document;if("querySelectorAll"in c)return c.querySelectorAll(b+"["+a+"]");var e=[];c=c.getElementsByTagName(b);for(var f=c.length;f--;)c[f].getAttribute(a)&&e.push(c[f]);return e}function Oa(a,b,c){return a===d?j:c===d&&a.getAttribute(b)||a.getAttribute(b)===c?a:a===document.body?j:Oa(a.parentNode,b,c)}
function Pa(a){var b,c;b="pageYOffset";c="scrollTop";if(a&&(a=Na("data-cb-scroll-element"))&&a.length)return a[0][c];if(qa(p[b]))return p[b];else if(document.body&&document.body[c])return document.body[c];else if(document.documentElement[c])return document.documentElement[c];return 0}function Qa(){var a=document,a=a[a.compatMode==="CSS1Compat"?"documentElement":"body"].clientHeight||0;window.innerHeight&&(a=Math.min(window.innerHeight,a));return a}
function Ra(a){a="scroll"+a;return Math.max(document.body[a],document.documentElement[a])||0}function Sa(a,b,c){var e=a.ownerDocument.documentElement,f=0,i=v(c)?c+1:-1;sa(b)?(b=b.toLowerCase(),c=function(a){return(a=a.nodeName)&&a.toLowerCase()===b}):c=b;for(;a&&a!==e&&f!==i;){if(c(a))return a;a=a.parentNode;f++}return h}function Ta(a){return a.nodeName&&a.nodeName.toLowerCase()==="a"&&(!a.namespaceURI||a.namespaceURI==="http://www.w3.org/1999/xhtml")}
function Ua(a){a=a||window.event;return!a?h:Sa(a.target||a.srcElement,Ta,10)}function Va(a,b){var c=document.createElement(a);s(b,function(a,b){c.setAttribute(b,a)});return c};function Wa(){this.oa={};this.Ua=1}function y(a,b,c,e){a.Ua++;a.oa[b]=a.oa[b]||{};a.oa[b][a.Ua]=[c,e];return a.Ua}function Xa(a,b){if(sa(b))a.oa[b]=d,delete a.oa[b];else if(qa(b)){var c=g;s(a.oa,function(a){s(a,function(f,i){if(parseInt(i,10)===b)return a[i]=d,delete a[i],c=j});return c})}}Wa.prototype.ya=function(a,b){if(this.oa[a]){var c=arguments.length>1?Array.prototype.slice.call(arguments,1):[];s(this.oa[a],function(a){var b;a&&a.length===2&&(b=a[0],a=a[1],b.apply(a,c))})}};
Wa.prototype.addEventListener=function(a,b){var c=y(this,a,b);b._cbEventId=c};Wa.prototype.removeEventListener=function(a,b){this.oa[a]&&this.oa[a][b._cbEventId]&&this.oa[a][b._cbEventId][0]===b&&Xa(this,b._cbEventId)};var z=new Wa;var A={};
A.G=function(){A.Lb?A.qb("pageload"):(A.Mc=[{target:p,event:"scroll"},{target:document.body,event:"keydown"},{target:document.body,event:"mousemove"},{target:p,event:"resize"},{target:document.body,event:"mousedown"}],A.wb=h,A.Ia=h,A.Kb={},A.Jb={},A.tc={},A.yb={},s(A.Mc,function(a){var b=a.event;w(a.target,b,function(a){A.qb.call(A,b,a)})}),y(z,"f",function(){A.qb("focus")}),A.qb("pageload"),w(document.body,"click",function(a){(a=Ua(a))&&z.ya("c",a)},g),w(document.body,"contextmenu",function(a){(a=Ua(a))&&
z.ya("r",a)}),A.Lb=g)};A.Tc=function(){var a,b=A.tc.keydown;if(b===d)return j;b=t()-b;return b<=(a||15E3)&&b>=0};A.Ya=function(a,b){var c=A.yb[a];if(!c)return"";var b=b||t(),e,f=0;s(c,function(a){e=Math.floor((b-a)/1E3);e>=0&&e<16&&(f|=1<<e)});c=("0000"+f.toString(16)).slice(-4);return c=="0000"?"":c};A.Sd=function(){A.yb={}};A.jc=100;
A.qb=function(a,b){if(!b)b=window.event;if(b&&a==="keydown"){var c=b.keyCode?b.keyCode:b.which;if(c===32||c>36&&c<41)a="scroll"}A.Xd(a);if(A.wb===h)A.Gc(a);else if(!A.Ia||ga[A.Ia]<ga[a]||ha[A.Ia]<ha[a])A.Ia=a};A.Xd=function(a){var b=t();A.tc[a]=b;var c=A.yb[a];c?c.length<2?c.push(b):c[c.length-2]>b-1E3?c[c.length-1]=b:c.push(b):c=[b];c.length>32&&c.shift();A.yb[a]=c};
A.Gc=function(a){A.wb=Ja(A.Zc,A.jc);z.ya("a");A.Kb[a]!==h&&Ka(A.Kb[a]);A.Jb[a]!==h&&Ka(A.Jb[a]);A.Fc(a,A.Kb,ga,"i");A.Fc(a,A.Jb,ha,"j")};A.Fc=function(a,b,c,e){b[a]=Ja(function(){Ka(b[a]);delete b[a];var c=j;s(b,function(){c=g;return j});c||z.ya(e)},c[a]+A.jc)};A.Zc=function(){Ka(A.wb);A.wb=h;if(A.Ia)A.Gc(A.Ia),A.Ia=h};var Ya,Za,$a,ab,bb;(function(){var a,b;s(["","moz","o","ms","webkit"],function(c){a=(c+"Hidden").charAt(0).toLowerCase()+(c+"Hidden").slice(1);if(typeof p.document[a]==="boolean")return b=c,j});b!==d&&(ab=a,bb=(b+"VisibilityState").charAt(0).toLowerCase()+(b+"VisibilityState").slice(1),$a=b+"visibilitychange")})();var cb=j;function db(){cb=bb&&p.document[bb]==="prerender"?g:j}function eb(){Za=g;z.ya("f")}function fb(){Za=j;z.ya("b")}
function gb(a,b,c){p.addEventListener?p.addEventListener(a,c,j):p.document.attachEvent&&p.document.attachEvent(b,c)}function hb(){var a=g;p.document.hasFocus&&(a=p.document.hasFocus());var b=j;ab&&(b=p.document[ab]);return a&&!b}function ib(){hb()?eb():fb()}function jb(a){db();if(cb){var b=j,c=function(){b||(db(),cb||(b=g,a(),p.window.setTimeout(function(){p.document.removeEventListener($a,c,j)},100)))};p.document.addEventListener($a,c,j)}else a()};function kb(){this.k=p._sf_async_config||{};this.oc=u(this.zc,this)}kb.prototype.G=function(){this.Bc=0};kb.prototype.zc=k();kb.prototype.eb=function(a){if(!cb){var b=this.oc,c;c=new Image(1,1);if(b)c.onerror=b;c.src=a}};kb.prototype.xa=function(){this.oc=h};function lb(a){var b={};a&&(a.charAt(0)=="?"&&(a=a.substring(1)),a=a.replace("+"," "),s(a.split(/[&;]/g),function(a){a=a.split("=");b[decodeURIComponent(a[0])]=decodeURIComponent(a[1])}));return b}function mb(a,b){var c="",e=p.location.href.split("?");if(e.length){var e=lb(e[1]),f=b||a;e[f]&&(c=e[f])}return c}function nb(a,b){return!b?g:a==="http:"&&b==="80"||a==="https:"&&b==="443"}
function ob(a){var b=[];s(pb,function(c){var e=a[c];v(e)&&(Object.prototype.toString.call(e)==="[object Array]"?s(e,function(a){b.push(c+"="+a)}):e&&e.constructor===Object?s(e,function(a,c){b.push(c+"="+a)}):((e+"").length||c=="r")&&b.push(c+"="+e))});b.push("_");return b.join("&")}
function qb(a){var b={hostname:"",pathname:"",search:"",protocol:"",port:"",hash:""};if(!a)return b;var c=document.createElement("a"),e=p.location;if(!/^https?:/.test(a)&&a.indexOf("javascript:")!==0)if(a.indexOf("//")===0)a=e.protocol+a;else if(a.indexOf("/")===0)var f=nb(e.protocol,e.port)?"":e.port,a=e.protocol+"//"+e.hostname+(f?":"+f:"")+a;else{var f=document.baseURI||e.href,i=f.indexOf("?");i===-1&&(i=f.indexOf("#"));if(i===-1)i=f.length;i=f.lastIndexOf("/",i);a=i===-1?"/"+a:f.substr(0,i)+"/"+
a}c.href=a;b.hostname=c.hostname;b.pathname=c.pathname;b.search=c.search;b.protocol=c.protocol;b.port=c.port;b.hash=c.hash;if(b.pathname.charAt(0)!=="/")b.pathname="/"+b.pathname;if(b.hostname==="")b.hostname=e.hostname;if(b.protocol==="")b.protocol=e.protocol;if(b.protocol==="javascript:")b.pathname="",b.hostname="",b.port="",b.hash="";if(nb(b.protocol,b.port)||b.port==="0")b.port="";return b}
function rb(a){var b=a.protocol;a.hostname&&(b+="//"+a.hostname,a.port&&(b+=":"+a.port));return b+a.pathname+a.search+a.hash};function D(a,b,c){a[b]=a[b]||c}function sb(a,b){for(var c=p[a]||[];c.length;)b(c.shift());p[a]={push:b}}function tb(a){s(document.getElementsByTagName("script"),function(b){if(b.src.match(/chartbeat.js/))return b=lb(b.src.split("?")[1]),D(a,"uid",b.uid),D(a,"domain",b.domain),j})}function ub(a,b){return a[b]?encodeURIComponent(a[b]):""}function vb(a){var b={};s(a,function(a,e){e.charAt(0)=="_"&&(b[e]=a)});return b};var F={};F.Wc=function(){try{F.create("_cb_test","1",1);var a=F.F("_cb_test");F.remove("_cb_test");return a==="1"}catch(b){return j}};F.F=function(a){a+="=";var b="";s(document.cookie.split(";"),function(c){for(;c.charAt(0)===" ";)c=c.substring(1,c.length);if(c.indexOf(a)===0)return b=c.substring(a.length,c.length),j});return b};
F.create=function(a,b,c){var e=p._sf_async_config;if(e&&e.noCookies)return"";e=new Date;e.setTime(t()+c*1E3);a=a+"="+b+("; expires="+e.toGMTString())+"; path=/";return document.cookie=a};F.remove=function(a){return F.F(a)?F.create(a,"",-86400):""};var G={};G.Z=function(a){var b=p._sf_async_config;if(!a&&b&&b.noCookies)return h;if(G.Z.Db!==d)return G.Z.Db;var a=t()+"",c,e;try{if((e=p.localStorage).setItem(a,a),c=e.getItem(a)===a,e.removeItem(a),c)return G.Z.Db=e}catch(f){}return G.Z.Db=h};G.F=function(a){var b=G.Z();if(!b)return"";var c=b.getItem(a+"_expires");return c&&(c=+c,!isNaN(c)&&t()>c)?(G.remove(a),""):b.getItem(a)||""};
G.create=function(a,b,c){var e=G.Z();if(e){var f=new Date;f.setTime(t()+c*1E3);try{e.setItem(a,b),e.setItem(a+"_expires",f.getTime())}catch(i){}}};G.remove=function(a){var b=G.Z();b&&(b.removeItem(a),b.removeItem(a+"_expires"))};function wb(a){this.sb=a||"";this.$c=G.Z()!==h||F.Wc();this.bc=j;xb(this)}n=wb.prototype;n.isSupported=l("$c");
function xb(a){if(!F.F("_cb_ls")){var b=G.Z()!==h,c=F.F("_SUPERFLY_nosample");c&&s(["","_v_","_p_"],function(b){a.create(b+"_SUPERFLY_nosample",c,600,g)});var e=F.F("_chartbeat3");e&&(a.create("_v__chartbeat3",e,2592E3,g),F.remove("_chartbeat3"));b&&((b=F.F("_chartbeat2"))&&a.create("_chartbeat2",b,63072E3,g),(b=F.F("_chartbeat_uuniq"))&&a.create("_chartbeat_uuniq",b,63072E3,g),(b=F.F("_chartbeat5"))&&a.create("_chartbeat5",b,60,g));F.create("_cb_ls","1",2592E3)}}
function yb(a){var b=a.bc;a.bc=j;return b}n.create=function(a,b,c,e){a=e?a:this.sb+a;(G.Z()?G:F).create(a,b,c);G.Z()&&F.create(a,b,c)};n.update=function(a,b,c,e,f,i,q){a=e?a:this.sb+a;f=sa(f)?f:"::";e=(e=this.F(a,g))?e.split(f):[];if(q&&e.length){var B=q(b),o=wa(e,function(a){return q(a)===B});o!==-1&&e.splice(o,1)}qa(i)&&e.length>=i&&e.splice(0,e.length-i+1);e.push(b);this.create(a,e.join(f),c,g)};
n.F=function(a,b){var a=b?a:this.sb+a,c=(G.Z()?G:F).F(a);if(!c&&G.Z()&&(c=F.F(a))&&F.F("_cb_ls")){this.bc=g;var e;switch(a){case "_SUPERFLY_nosample":e=600;break;case "_chartbeat4":e=3600;break;case "_cb_cp":e=3600;break;case "_chartbeat3":e=2592E3;break;default:e=63072E3}G.create(a,c,e)}return c};n.remove=function(a,b){a=b?a:this.sb+a;(G.Z()?G:F).remove(a);G.Z()&&F.remove(a)};function zb(a){var b=h;if(a&&(b=Ab()))return b;var c=p.location,b=Bb(c.pathname),a=c.search||"",a=a.replace(/PHPSESSID=[^&]+/,""),e=/&utm_[^=]+=[^&]+/ig;(c=e.exec(c.search))&&(a=a.replace(e,""));e=/\?utm_[^=]+=[^&]+(.*)/i;(c=e.exec(a))&&(a=a.replace(e,c[1]!=""?"?"+c[1]:""));return b+a}function Ab(){var a=h;s(document.getElementsByTagName("link"),function(b){if(b.rel=="canonical")return b=qb(b.href),a=Bb(b.pathname)+b.search+b.hash,j});return a}
for(var Cb={},Db=0;Db<81;Db++)Cb["0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz-._~!$&'()*+,;=:@[]".charCodeAt(Db)]=g;function Eb(a,b){if(a==="%")return"%25";var c=parseInt(b,16);return Cb[c]?String.fromCharCode(c):"%"+b.toUpperCase()}function Bb(a){if(!sa(a))return a;a=a.replace(/%([0-9A-Fa-f]{2})?/g,Eb);return a=a.replace(/[^0-9A-Za-z\-._~!$&'()*+,;=:@\/\[\]?#%]+/g,encodeURIComponent)};var H={Pc:{IDLE:0,Oc:1,Nc:2,Ab:3},Qc:{IDLE:0,Oc:1,Nc:2,Ab:3},pa:0,qa:0};H.G=function(){if(!H.Lb)y(z,"a",H.fd,H),y(z,"i",H.kd,H),y(z,"f",H.hd,H),y(z,"b",H.gd,H),y(z,"j",H.jd,H),H.Lb=g};H.M=function(){return H.pa};H.ed=function(){return H.qa};H.fd=function(){H.pa===1?H.Fa(3):H.pa===0&&H.Fa(2);H.qa===1?H.Ea(3):H.qa===0&&H.Ea(2)};H.kd=function(){H.pa===3?H.Fa(1):H.pa===2&&H.Fa(0)};H.jd=function(){H.qa===3?H.Ea(1):H.qa===2&&H.Ea(0)};H.hd=function(){(H.pa===0||H.pa===2)&&H.Fa(3);(H.qa===0||H.qa===2)&&H.Ea(3)};
H.gd=function(){H.pa===3?H.Fa(2):H.pa===1&&H.Fa(0);H.qa===3?H.Ea(2):H.qa===1&&H.Ea(0)};H.Fa=function(a){H.pa=a;z.ya("s",a)};H.Ea=function(a){H.qa=a;z.ya("x",a)};function Fb(a,b){this.Ib=a||d;this.Pb=b||d;this.Pa=this.va=0;this.sc=u(this.pd,this);this.ac=this.ra=h}n=Fb.prototype;n.G=function(){this.Pa=this.va=0;this.ra=h;this.ac=y(z,"s",this.$a,this);this.$a(H.M())};n.$a=function(a){Ia(this.ra);this.ra=h;if(a===H.Pc.Ab)this.ra=Ha(this.sc,1E3)};n.pd=function(){if(this.Ib===d||this.Ib())this.va++,this.Pa++,this.Pb&&this.Pb()};n.terminate=function(){Ia(this.ra);this.ra=h;Xa(z,this.ac)};n.xa=function(){this.terminate();this.Pb=this.Ib=d};function Gb(a,b){Fb.call(this,a,b)}ea(Gb,Fb);Gb.prototype.G=function(){this.Pa=this.va=0;this.ra=h;this.ac=y(z,"x",this.$a,this);this.$a(H.ed())};Gb.prototype.$a=function(a){Ia(this.ra);this.ra=h;if(a===H.Qc.Ab)this.ra=Ha(this.sc,1E3)};function I(){kb.call(this);this.La=[];this.H=new wb(this.Ic);this.na=new Fb;this.Ja=new Gb;this.Rb=u(this.bb,this);w(p,"unload",this.Rb);jb(u(this.G,this))}ea(I,kb);n=I.prototype;n.Yb=g;
n.G=function(){I.ma.G.call(this);this.lb=this.Qa=0;this.Ga=t();this.Da=la(Hb(this));this.Wb=g;this.ob=72E5;if(this.Yb){var a=+this.k.sessionLength;if(!isNaN(a))this.ob=a*6E4}a=J(Ib);if(!a){var a=[],b=this.H.F("_chartbeat2",g);b.length>0&&(a=b.split("."));a.length>4&&(a=[]);var b=t(),c=b-+(a[1]||0),e=b-+(a[2]||0),f=Jb,c=a[0]&&c>18E5&&e<2592E6?0:1;K()[f]=c;c="1";e=a&&+a[2];f=a&&a[3];if(a&&e&&f)if(c=Math.abs((ua(b)-ua(e))/864E5)){c=Math.min(c,16)-1;for(e="";c--;)e+=0;c=(f+e+"1").slice(-16)}else c=f;
f=c;a[0]||(a[0]=this.k.utoken||la(Hb(this),3),a[1]=b);a[2]=b;a[3]=f;this.k.utoken=this.gb;this.H.create("_chartbeat2",a.join("."),63072E3,g);b=Ib;K()[b]=a}this.fe=a.join(".");var i;f=+a[1];c=+a[2];if((b=a[3])&&f&&c)i=(Math.min((Math.abs((ua(c)-ua(f))/864E5)||0)+1,16,b.length)-1).toString(16),i+=("0000"+parseInt(b,2).toString(16)).slice(-4);this.rc=i;this.Nb=J(Jb,1);this.gb=a[0];this.na.G();this.Ja.G();H.G();A.G();Ya||(Za=hb(),$a&&p.document.addEventListener&&p.document.addEventListener($a,ib,j),gb("focus",
"onfocusin",eb),gb("blur","onfocusout",fb),Za&&eb(),Ya=g);this.ab=0;this.Sc=y(z,"a",this.sd,this)};function Kb(a){if(!a.H.F("_SUPERFLY_nosample")&&!cb)a.rd?a.ub():(a.rd=g,!p._sf_async_config&&!p._cbq?(a.rb=u(a.ub,a),w(p,"load",a.rb)):a.ub())}n.ub=function(){var a=p._sf_startpt,b=p._sf_endpt;if(qa(a))this.cb=qa(b)?b-a:t()-a;A.G();a=u(this.ka,this);this.Oa=Ha(a,15E3);this.ka()};
n.ka=function(){var a=this.na.Pa,a=this.k.reading&&+this.k.reading||a>0;if(this.lb<this.Qa&&!a)this.lb++;else{var b;if(Ga===d)b=p.navigator.userAgent,Ga=b.indexOf("AppleWebKit")>0&&b.indexOf("FBIOS")>0;b=Ga;b&&!a?this.lb++:(a?this.Qa=0:this.Cb(),this.lb=0,this.La.push(0),this.La.length>18&&this.La.shift(),this.Yb&&t()-this.Ga>=this.ob?this.terminate():this.Ta())}};
n.zc=function(){this.La.push(1);var a=0;s(this.La,function(b){a+=b});a<3?(this.Wb=g,this.Cb()):(this.terminate(),this.H.create("_SUPERFLY_nosample","1",600))};n.bb=k();n.sd=function(){var a=Lb(this);this.ab=Math.max(this.ab,a)};function Lb(a){return Pa(!!a.k.scrollElement)}n.Cb=function(){var a=this.Qa;this.Qa=a=a?Math.min(a*2,16):1};n.kb=function(){this.bb();this.terminate()};n.Hc=function(){this.G();Kb(this)};
function Mb(a){if(a.k.virtualReferrer)return g;a=(document.referrer||"").indexOf("://"+p.location.hostname+"/");return a!=-1&&a<9}function Nb(a){a=a.k.virtualReferrer;if(!a&&(a=document.referrer||"")){var b=qb(a);if(b.protocol==="http:"||b.protocol==="https:")b.pathname=Bb(b.pathname),a=rb(b)}return encodeURIComponent(a)}function Ob(a){a=a.k.title.slice(0,100);return encodeURIComponent(a)}function Hb(a){a=[Nb(a),Ra("Width"),Ra("Height")];return na(a)}
function Pb(a){var b=[],c=a.H.F("_chartbeat4");c&&(s(c.split("::"),function(a){b.push(encodeURIComponent(a))}),a.H.remove("_chartbeat4"));return b}n.terminate=function(){this.na.terminate();this.Ja.terminate();Xa(z,this.Sc);this.rb!==d&&pa(p,"load",this.rb);Ia(this.Oa);var a=Ib;K()[a]=d;a=Jb;K()[a]=d};n.xa=function(){this.terminate();pa(p,"unload",this.Rb);this.Rb=this.rb=this.H=this.La=this.k=h;this.na.xa();this.na=h;this.Ja.xa();this.Ja=h;I.ma.xa.call(this)};var Ib="d",Jb="n";function J(a,b){var c=K();return v(b)&&!v(c[a])?b:c[a]}function K(){v(p._cb_shared)||(p._cb_shared={});return p._cb_shared};function Qb(a){for(var b=J("m")||[];b.length;)a(b.shift());a={push:a};K().m=a};function Rb(a){var b=a.offsetLeft,c=a.offsetTop,e=Sb(a);b+=e.x;c+=e.y;for(var f=j,e=a.offsetParent;a&&a!==d&&a!==document.body;){if(a===e)e=Sb(a),b+=a.offsetLeft+e.x,c+=a.offsetTop+e.y,e=a.offsetParent;if(Tb(a,["position"]).position==="fixed"){f=g;break}a=a.parentElement}f&&(b+=0,c+=0);return{x:b,y:c}}
function Tb(a,b){var c={},e,f;p.getComputedStyle?e=p.getComputedStyle(a,h):a.currentStyle?f="currentStyle":a.style&&(f="style");s(b,function(b){c[b]=e?e[b]||e.getPropertyValue(b):a[f][b]});return c}var Ub=/matrix(3d)?\((.*)\)/;function Sb(a){var b={x:0,y:0},a=Tb(a,["transform"]).transform;if(!sa(a))return b;var c=a.match(Ub);if(!c)return b;var a=c[2].split(", "),e;v(c[1])?(c=12,e=13):(c=4,e=5);b.x=parseInt(a[c],10);b.y=parseInt(a[e],10);return b};function Vb(){var a=p.location.href,a=a.replace(/-{2,}/g,"-"),a=qb(a);a.pathname=Bb(a.pathname);return a}
function Wb(a){var b=F.F("_chartbeat6");if(!b)return h;var b=b.split("::"),c,e;if(b.length===1)c=b[0].split(","),e=0;else{var f,i=Vb(),q=rb(i);s(b,function(a,b){var i=a.split(","),o=Ea(q,decodeURIComponent(i[0]));if(o===0)return c=i,e=b,j;if(f===d||o<f)f=o,c=i,e=b})}b.splice(e,1);a="_chartbeat6="+b.join("::")+Xb(a);document.cookie=a;var a=[],b=c[0],i=c[1],B=c[2];c.splice(0,3);for(var o=c.length/2,C=0;C<o;C++)a.push({ce:b,origin:i,Ra:B,bd:c[C*2],Yd:c[C*2+1]});return a}
function Xb(a){var b="",c;if(!(a&&a.constructor===Object))return b;a.wc&&(c=new Date,c.setTime(c.getTime()+a.wc),b+="; expires="+c.toGMTString());a.domain&&(b+="; domain="+a.domain);a.path&&(b+="; path="+a.path);return b}function Yb(a){var b=a.topStorageDomain,a=a.domain,c=p.location.hostname;return b?b:Zb(c,a)?a:c.replace(/^www\./,"")}function Zb(a,b){if(a===b)return g;for(var c=b.split("."),e=a.split(".");c.length;){if(e.length===0)return j;if(c.pop()!==e.pop())return j}return g}
function $b(a,b,c,e){this.dd=a;this.cd=b;this.Zd=c;this.Ra=e};function ac(a,b){for(var c=b||document.documentElement,e=[],f=h,i=a,q,B,o,C,M,P;i&&i!==c;){q=i.nodeName.toLowerCase();f=i;B=f.nodeName;if((i=i.parentNode)&&i!==document.documentElement){o=i.children;C=0;for(M=0,P=o.length;M<P;M++){if(f===o[M]){q+="["+(1+M-C)+"]";break}o[M].nodeName!==B&&C++}}e.unshift(q)}return e.join("/")};function bc(){this.Ic="_t_";I.call(this)}ea(bc,I);n=bc.prototype;
n.G=function(){bc.ma.G.call(this);tb(this.k);var a=p.location;D(this.k,"mabServer","mabping.chartbeat.net");D(this.k,"title",document.title);D(this.k,"domain",a.hostname);D(this.k,"path",zb(!!this.k.useCanonical));this.ta=oa(a.hostname);this.k.domain=oa(this.k.domain);this.Wd=Yb(this.k);this.Xa=this.nb=j;this.pc=[];var b=this,a=Wb({domain:"."+this.Wd,wc:6E4,path:"/"});if(a!==h)this.nb=g,s(a,function(a){b.pc.push(new $b(a.origin,a.bd,a.Yd,a.Ra))});this.xc=0;this.vb=h;Qb(u(this.od,this))};
n.Ta=function(){var a=this.na.va,b=cc(this),c,e=this;this.nb&&s(this.pc,function(f){c=b+"&x="+f.cd+"&v="+f.Zd+"&ml="+f.Ra+"&xo="+f.dd+"&e="+a;e.eb(c)});!this.Xa&&this.vb&&dc(this,this.vb);this.Xa=g};n.ub=function(){var a=p._sf_startpt,b=p._sf_endpt;if(qa(a))this.cb=qa(b)?b-a:t()-a;A.G();if(this.nb)a=u(this.ka,this),this.Oa=Ha(a,500);this.ka()};n.ka=function(){var a,b;this.Xa?(a=this.na.va,b=this.xc*15,a-b>=15&&(this.Ta(),this.xc+=1),a>=45&&this.terminate()):this.Ta()};
function cc(a){var b=a.k;return(p.location.protocol||"http:")+"//"+b.mabServer+"/ping/mab?h="+encodeURIComponent(b.domain)+"&p="+encodeURIComponent(b.path)+"&d="+encodeURIComponent(a.ta)+"&u="+a.gb+"&c="+Math.round((t()-a.Ga)/600)/100}n.bb=k();n.Ud=function(a){var b=a.d,c=h;b!==h&&(c={Zb:b.s,Ra:b.g,vc:b.m});a={status:a.s,data:c,code:a.c,message:a.m};this.Xa?dc(this,a):this.vb=a};
function dc(a,b){var c=cc(a),e=b.status,f=b.data;if(e=="s"&&f!==h){var i=u(a.eb,a);f.Zb&&f.Zb.constructor===Object&&s(f.Zb,function(a,b){i(c+"&x="+b+"&v="+a+"&ml="+f.Ra+"&e=-1")});Object.prototype.toString.call(f.vc)==="[object Array]"&&s(f.vc,function(a){i(c+"&me=3&ml="+f.Ra+"&x="+a)})}else e=="e"&&a.eb(c+"&me="+b.code)}n.od=function(a,b){for(var c=0,e=arguments.length;c<e;c++){var a=arguments[c],f=a.shift();f==="t"?this.Ud.apply(this,a):f==="v"&&this.Td.apply(this,a)}};
n.kb=function(){K().m=[];v(this.fc)&&this.fc();bc.ma.kb.call(this)};n.Td=function(a){this.fc=a};n.terminate=function(){this.fc=this.de=d;this.vb=h;this.Xa=this.nb=d;bc.ma.terminate.call(this)};if(!p.pSUPERFLY_mab){var ec=new bc,fc={};fc.evps=u(ec.kb,ec);fc.svps=u(ec.Hc,ec);p.pSUPERFLY_mab=fc;Kb(ec)};var gc,hc,ic;
function jc(a){if(a.origin==="https://chartbeat.com"&&(a=String(a.data),a.indexOf("_cb_hud_version=")===0)){var b=a.substr(16);kc();if(b!=="NONE")b=b.indexOf("HUD2.")===0?b.substr(5):"OLD",a="https://static.chartbeat.com/js/inpage.js",b!=="OLD"&&(a="https://static2.chartbeat.com/frontend_ng/hud/hud-inpage/hud-inpage-"+b+".js"),b=v(d)?d:{},b.src=a,a=Va("script",b),a.setAttribute("type","text/javascript"),b=document.head||document.getElementsByTagName("head")[0],v(d)?d.appendChild(a):b&&b.appendChild(a)}}
function kc(){Ka(hc);hc=d;pa(p,"message",jc);ic&&ic.parentNode&&ic.parentNode.removeChild(ic);ic=d};function lc(){var a=p._sf_async_config&&p._sf_async_config.domain;if(a&&!gc){gc=g;a="https://chartbeat.com/publishing/hud2/versioninfo/?host="+encodeURIComponent(a);w(p,"message",jc);hc=Ja(kc,1E4);var b=v(d)?d:{};b.src=a;a=Va("iframe",b);a.style.display="none";v(d)?d.appendChild(a):document.body&&document.body.appendChild(a);ic=a}}
function mc(a){if(/[\/.]chartbeat\.com$/.test(a.origin)){var b=G.Z(g),c=String(a.data);b&&c.indexOf("_cb_ip")==0&&(b.setItem("_cb_ip","1"),a.source.postMessage(1,a.origin),lc(),pa(p,"message",mc))}};function nc(){"postMessage"in window&&w(p,"message",u(this.ld,this));I.call(this);sb("_cbq",u(this.Ec,this))}ea(nc,I);
nc.prototype.G=function(){nc.ma.G.call(this);var a=this.gb;K().u=a;a=this.Da;K().t=a;this.Bb=h;tb(this.k);a=p.location;D(this.k,"pingServer","ping.chartbeat.net");D(this.k,"title",document.title);D(this.k,"domain",a.hostname);this.k.path=this.k.path?Bb(this.k.path):zb(!!this.k.useCanonical);this.ta=oa(a.hostname);this.k.domain=oa(this.k.domain);this.Uc=y(z,"c",this.xd,this);this.Vc=y(z,"r",this.yd,this);this.Na=h};nc.prototype.Rc=function(a){this.Bb=a};
nc.prototype.bb=function(){this.H.update("_chartbeat4",["t="+this.Da,"E="+this.na.va,"EE="+this.Ja.va,"x="+Lb(this),"c="+Math.round((t()-this.Ga)/600)/100,"y="+Ra("Height"),"w="+Qa()].join("&"),3600,d,d,1)};var pb="h,p,u,d,g,g0,g1,g3,g4,n,nc,f,c,x,m,y,o,w,j,R,W,I,E,e,v,r,vp,K,l1,KK,PA,b,A,_c,_m,t,V,z,i,L,tz,l,,sn,C,eS,eM,eD,eK,eR,EE".split(",");n=nc.prototype;
n.Ta=function(a){this.Bc++;var b={};b.g=this.k.uid;b.g0=ub(this.k,"sections");b.g1=ub(this.k,"authors");b.g2=ub(this.k,"zone");b.g3=ub(this.k,"sponsorName");b.g4=ub(this.k,"type");!this.k.noCookies&&this.H.isSupported()?b.n=this.Nb:b.nc=1;b.c=Math.round((t()-this.Ga)/600)/100;b.E=this.na.va;b.EE=this.Ja.va;var c=Lb(this);this.ab=Math.max(this.ab,c);b.x=c;b.m=this.ab;b.y=Ra("Height");b.o=Ra("Width");b.w=Qa();b.b=this.cb?this.cb:"";if(this.rc)b.f=this.rc;b[""]=vb(this.k);b.t=this.Da;b.V=69;b.tz=(new Date).getTimezoneOffset();
b.sn=this.Bc;c=this.na.Pa;b.h=encodeURIComponent(this.k.domain);b.p=encodeURIComponent(this.k.path);b.u=this.gb;b.d=encodeURIComponent(this.ta);b.j=Math.round((this.Qa+2)*15E3/1E3);b.R=0;b.W=0;b.I=0;var e=b.c*6E4+this.Ga;b.eD=A.Ya("mousedown",e);b.eM=A.Ya("mousemove",e);b.eK=A.Ya("keydown",e);b.eR=A.Ya("resize",e);b.eS=A.Ya("scroll",e);A.Sd();A.Tc()?b.W=1:this.k.reading&&+this.k.reading||c>0||b.c<0.09?b.R=1:b.I=1;b.e=c;c=Mb(this);if(this.Wb){this.Wb=j;if(c)this.Na=oc(this);b.i=Ob(this);e=this.k.hudTrackable;
e!==d&&(b.L=e?"1":"0");this.k.alias&&(b.PA=encodeURIComponent(this.k.alias))}if(c){if(this.Na){if(b.v=encodeURIComponent(this.Na.path),b.K=pc(this.Na),this.Na.Ob>1)b.l1=this.Na.Ob}else b.v=Nb(this);this.k.virtualReferrer&&(b.vp=1)}else b.r=Nb(this);c=La(b.v);K().v=c;c=La(b.r);K().r=c;b.A=this.Bb?this.Bb:"";b._c=mb("utm_campaign",this.k.campaignTag);b._m=mb("utm_medium",this.k.mediumTag);b.z=Pb(this);b.C=this.k.mobileApp?1:"";b.KK=a?pc(a):"";b.l=yb(this.H)?1:"";this.na.Pa=0;this.eb((p.location.protocol||
"http:")+"//"+this.k.pingServer+"/ping?"+ob(b))};
n.ld=function(a){var b=this.k;if(a.origin==="http://"+(b.playerdomain||this.ta)){var c=a.data;if(sa(c)&&c.indexOf("cbqpush::")===0)a=c.split("::"),a.length==3&&(a=a.slice(1),a[0].indexOf("_")===0&&this.Ec(a));else if(c=="cbdata?"){var c="&u="+J("u"),e="&t="+J("t"),f="&v="+J("v"),i="&r="+J("r"),b="domain="+encodeURIComponent(b.domain)+"&uid="+encodeURIComponent(b.uid)+"&path="+encodeURIComponent(b.path)+"&title="+Ob(this)+"&referrer="+Nb(this)+"&internal="+(Mb(this)?"1":"0")+"&subdomain="+encodeURIComponent(this.ta)+
c+e+f+i+"&utoken="+this.gb;a.source.postMessage(b,"*")}}};n.Ec=function(a){a[0]==="_demo"&&this.k._demo?this.k._demo=this.k._demo+"%2C"+a[1]:this.k[a[0]]=a[1];this.Qa=0};function qc(a){a=a.replace(/-{2,}/g,"-");a=qb(a);a.pathname=Bb(a.pathname);return a}n.xd=function(a){rc(this,a,"c")};n.yd=function(a){rc(this,a,"r")};
function rc(a,b,c){if(a.Yb&&t()-a.Ga>=a.ob)a.terminate();else{var e=b.href||"",e=qc(e);if(!(e.hostname!==p.location.hostname||e.protocol.indexOf("http")!==0)){var e=rb(e),f=Sa(b,function(a){return a.id}),i=ac(b,f);f&&(i&&(i="/"+i),i="*[@id='"+f.id+"']"+i);f=la(i);b=Rb(b);c={left:b.x,top:b.y,path:a.k.path,href:e,ic:f,hc:i,$b:c,Ob:0};a.Ta(c);a.H.update("_chartbeat5",sc(c),60,j,d,5,function(a){a=a.split(",");return a[2]+","+a[3]})}}}
function pc(a){return[a.left,a.top,a.ic,encodeURIComponent(a.hc),a.$b,encodeURIComponent(a.href)].join("::")}function sc(a){var b=encodeURIComponent(a.hc),b=b.replace(/-/g,"%2D");b.length>512&&(b="");return[a.left,a.top,encodeURIComponent(a.path),encodeURIComponent(a.href),a.ic,b,a.$b].join(",")}
function oc(a){var b=a.H.F("_chartbeat5");if(!b)return h;var c=b.split("::"),b=c.length,e,f;if(b===1)e=c[0].split(","),f=0;else{var i,q=qc(p.location.href),B=rb(q);s(c,function(a,b){var c=a.split(","),q=Ea(B,decodeURIComponent(c[3]));if(q===0)return e=c,f=b,j;if(i===d||q<i)i=q,e=c,f=b})}c.splice(f,1);a.H.create("_chartbeat5",c.join("::"),60);(a=e[5])?(a=a.replace(/%2D/g,"-"),a=decodeURIComponent(a)):a="";return{left:e[0],top:e[1],path:decodeURIComponent(e[2]),href:decodeURIComponent(e[3]),ic:e[4]||
"",hc:a,$b:e.length>6?e[6]:"c",Ob:b}}n.terminate=function(){Xa(z,this.Uc);Xa(z,this.Vc);nc.ma.terminate.call(this)};var L="ct",O="s1";function Q(a){this.a=a;this.B=this.D=j;this.q=t();this.ia()}n=Q.prototype;n.ia=function(){this.a.currentTime()>0&&!this.a.paused&&!this.a.ended&&this.ga();this.a.on("play",u(this.ga,this));this.a.ready(u(this.la,this))};n.la=function(){this.fa=this.a.mediainfo;this.D=g};n.ga=function(){this.B=g};n.P=function(){return this.D&&this.N()!==""};
n.Gb=function(){var a;this.a.cb_configs&&this.a.cb_configs.domain?a=this.a.cb_configs.domain:!a&&p._sf_async_config&&p._sf_async_config.domain&&(a=p._sf_async_config.domain);return a};n.Hb=function(){var a;this.a.cb_configs&&this.a.cb_configs.uid?a=this.a.cb_configs.uid:!a&&p._sf_async_config&&p._sf_async_config.uid&&(a=p._sf_async_config.uid);return a};
n.N=function(){if(!this.fa)this.fa=this.a.mediainfo;return(this.fa&&this.fa.hasOwnProperty("name")?this.fa.name:this.a.el().getAttribute("title"))||""};n.O=function(){if(!this.fa)this.fa=this.a.mediainfo;return(this.fa&&this.fa.hasOwnProperty("id")?this.fa.id:this.a.el().attributes["data-video-id"]&&this.a.el().attributes["data-video-id"].value?this.a.el().attributes["data-video-id"].value:this.a.src())||""};n.X=function(){return L};n.Q=m("");n.da=function(){var a=this.a.duration();return x(a)};
n.M=function(){return!this.B?O:this.a.ended()?"s4":this.a.paused()?"s3":"s2"};n.Y=function(){var a=this.a.currentTime();return x(a)};n.U=m(-1);n.ca=function(){if(!this.fa)this.fa=this.a.mediainfo;return(this.fa&&this.fa.hasOwnProperty("thumbnail")?this.fa.thumbnail:this.a.poster())||""};n.$=k();n.T=k();n.ea=function(){return Fa(this.q)};
n.aa=function(){var a=[];this.a.cb_configs&&this.a.cb_configs.sections?a=this.a.cb_configs.sections.split(","):a.length==0&&p._sf_async_config&&p._sf_async_config.sections&&(a=p._sf_async_config.sections.split(","));if(a.length>0&&a[0]!=="")return a};n.S=function(){var a=[];this.a.cb_configs&&this.a.cb_configs.authors?a=this.a.cb_configs.authors.split(","):a.length==0&&p._sf_async_config&&p._sf_async_config.authors&&(a=p._sf_async_config.authors.split(","));if(a.length>0&&a[0]!=="")return a};
n.ba=m("BCN");Q.prototype.getStrategyName=Q.prototype.ba;Q.prototype.isReady=Q.prototype.P;Q.prototype.getHost=Q.prototype.Gb;Q.prototype.getUid=Q.prototype.Hb;Q.prototype.getTitle=Q.prototype.N;Q.prototype.getVideoPath=Q.prototype.O;Q.prototype.getContentType=Q.prototype.X;Q.prototype.getAdPosition=Q.prototype.Q;Q.prototype.getTotalDuration=Q.prototype.da;Q.prototype.getState=Q.prototype.M;Q.prototype.getCurrentPlayTime=Q.prototype.Y;Q.prototype.getBitrate=Q.prototype.U;
Q.prototype.getThumbnailPath=Q.prototype.ca;Q.prototype.getPlayerType=Q.prototype.$;Q.prototype.getAutoplayType=Q.prototype.T;Q.prototype.getViewStartTime=Q.prototype.ea;Q.prototype.getSections=Q.prototype.aa;Q.prototype.getAuthors=Q.prototype.S;Q.verify=function(a){return a.controlBar!==d};function R(a){this.Ua=this.ta=d;this.D=j;this.Dc=this.lc=-1;this.wa=h;this.a=a;this.B=j;this.Sb=g;this.q=t();this.Tb="";for(var a=window.experienceJSON.data.configuredProperties.plugins.list.split(" "),b=a.length,c=0;c<b;c++){var e=a[c];if((e.indexOf("chartbeat")>=0||e.indexOf("localhost")>=0)&&e.indexOf(".js")>=0){this.Tb=e;break}}if(this.Tb)a=lb(this.Tb),this.ta=a.domain,this.Ua=a.uid;a=window.brightcove;this.a=a.api.getExperience();b=this.a.getModule(a.api.modules.APIModules.EXPERIENCE);b.getReady()?
this.Ac():b.addEventListener(a.player.events.ExperienceEvent.TEMPLATE_READY,r(this.Ac,this))}n=R.prototype;
n.Ac=function(){var a=window.brightcove,b=this.a.getModule(a.api.modules.APIModules.VIDEO_PLAYER),c=this;b.getVideoDuration(function(a){c.lc=Math.round(a)});b.getCurrentVideo(function(a){c.wa=a});a=a.api.events.MediaEvent;b.addEventListener(a.PROGRESS,r(this.Hd,this));b.addEventListener(a.STOP,r(this.Jd,this));b.addEventListener(a.COMPLETE,r(this.zd,this));b.addEventListener(a.BEGIN,r(this.ga,this));this.D=g};n.Hd=function(a){this.Dc=a.position;this.Aa=this.Sb=j};n.Jd=function(){this.Sb=g};
n.zd=function(){this.Aa=g};n.ga=function(){this.Aa=j;if(!this.B)this.B=g};n.P=l("D");n.N=function(){var a="";this.wa&&(a=this.wa.displayName);return a};n.O=function(){var a="";this.wa&&(a="video@"+this.ta+"/"+this.wa.id);return a};n.X=function(){return L};n.Q=m("");n.da=l("lc");n.M=function(){return!this.B?O:this.Aa?"s4":this.Sb?"s3":"s2"};n.Y=function(){return x(this.Dc)};n.U=m(-1);n.ca=function(){var a="";this.wa&&(a=this.wa.thumbnailURL);return a};n.$=k();
n.ea=function(){return isNaN(this.q)?0:ya(this.q)};n.S=k();n.aa=function(){var a;this.wa&&(a=this.wa.tags);return a};n.T=m("unkn");n.ba=m("BC");n.Gb=l("ta");n.Hb=l("Ua");R.prototype.isReady=R.prototype.P;R.prototype.getTitle=R.prototype.N;R.prototype.getVideoPath=R.prototype.O;R.prototype.getContentType=R.prototype.X;R.prototype.getAdPosition=R.prototype.Q;R.prototype.getTotalDuration=R.prototype.da;R.prototype.getState=R.prototype.M;R.prototype.getCurrentPlayTime=R.prototype.Y;
R.prototype.getBitrate=R.prototype.U;R.prototype.getThumbnailPath=R.prototype.ca;R.prototype.getPlayerType=R.prototype.$;R.prototype.getViewStartTime=R.prototype.ea;R.prototype.getAuthors=R.prototype.S;R.prototype.getSections=R.prototype.aa;R.prototype.getAutoplayType=R.prototype.T;R.verify=function(a){return a===window.brightcove};R.prototype.getStrategyName=R.prototype.ba;R.prototype.getHost=R.prototype.Gb;R.prototype.getUid=R.prototype.Hb;function T(){this.a=window.flowplayer();this.B=this.D=j;this.q=t();this.za=this.Ca=d;this.xb=this.fb="";this.Mb=d;this.ia()}var tc=/url\(['"]?([^'"\)]*)['"]?\)/;n=T.prototype;
n.qc=function(){if(this.a.conf&&(this.xb=this.a.conf.title?this.a.conf.title:"",this.fb=this.a.conf.poster?this.a.conf.poster:"",this.xb&&this.fb))return g;var a=this.O(),b=Na("name","param"),c=d;s(b,function(b){if(b.attributes.name&&b.attributes.name.value==="flashvars"&&b.value.indexOf(a)!==-1)return c=b,j});c===d&&(b=Na("src","video"),s(b,function(b){if(b.attributes.src.value&&a.indexOf(b.attributes.src.value)!=-1)return c=b,j}));b=Oa(c,"data-swf");if(b===j)return j;var e=b.style.background;if(e){if(e=
e.match(tc))this.fb=e[1]}else this.fb=b.attributes.poster&&b.attributes.poster.value;this.xb=b.title;if(this.Mb!==d)clearInterval(this.Mb),this.D=g;return g};n.ia=function(){this.a.he?this.la():this.a.bind("ready",r(this.la,this));this.a.bind("resume",r(this.ga,this));this.a.ge&&this.ga()};n.la=function(){this.qc()===j?this.Mb=setInterval(r(this.qc,this),1E3):this.D=g};n.ga=function(){if(!this.B)this.B=g};n.P=l("D");n.N=l("xb");n.O=function(){return this.a.video.url||this.a.video.src};n.X=function(){return L};
n.Q=m("");n.da=function(){return this.a.video.duration};n.M=function(){return!this.B?O:this.a.ee?"s4":this.a.paused?"s3":"s2"};n.Y=function(){return x(this.a.video.time)};n.U=m(-1);n.ca=l("fb");n.$=k();n.T=k();n.ea=function(){return isNaN(this.q)?0:ya(this.q)};n.aa=l("Ca");n.S=l("za");n.ba=m("FP");T.prototype.getStrategyName=T.prototype.ba;T.prototype.isReady=T.prototype.P;T.prototype.getTitle=T.prototype.N;T.prototype.getVideoPath=T.prototype.O;T.prototype.getContentType=T.prototype.X;
T.prototype.getAdPosition=T.prototype.Q;T.prototype.getTotalDuration=T.prototype.da;T.prototype.getState=T.prototype.M;T.prototype.getCurrentPlayTime=T.prototype.Y;T.prototype.getBitrate=T.prototype.U;T.prototype.getThumbnailPath=T.prototype.ca;T.prototype.getPlayerType=T.prototype.$;T.prototype.getAutoplayType=T.prototype.T;T.prototype.getViewStartTime=T.prototype.ea;T.prototype.getSections=T.prototype.aa;T.prototype.getAuthors=T.prototype.S;T.verify=function(){return!!window.flowplayer};function U(a){this.a=a;this.zb=this.B=this.D=j;this.q=t();this.za=this.Ca=d;this.ia()}n=U.prototype;n.ia=function(){this.a.readyState>0&&this.la();this.a.currentTime>0&&!this.a.paused&&!this.a.ended&&this.ga();this.a.addEventListener("canplay",u(this.la,this));var a=u(this.ga,this);this.a.addEventListener("playing",a);this.a.addEventListener("webkitbeginfullscreen",a);this.a.addEventListener("webkitendfullscreen",u(this.Pd,this))};n.la=function(){this.D=g};n.ga=function(){this.B=g;this.zb=j};
n.Pd=function(){this.zb=g};n.P=l("D");n.N=function(){return this.a.attributes.title&&this.a.attributes.title.value||""};n.O=function(){return this.a.currentSrc||""};n.X=function(){return L};n.Q=m("");n.da=function(){return x(this.a.duration)};n.M=function(){return!this.B?O:this.a.ended||this.zb&&this.a.currentTime==this.a.duration?"s4":this.a.paused||this.zb?"s3":"s2"};n.Y=function(){return x(this.a.currentTime)};n.U=m(-1);n.ca=function(){return this.a.poster||""};n.$=k();
n.T=function(){return this.a.autoplay?"auto":"man"};n.ea=function(){return Fa(this.q)};n.aa=l("Ca");n.S=l("za");n.ba=m("H5");U.prototype.getStrategyName=U.prototype.ba;U.prototype.isReady=U.prototype.P;U.prototype.getTitle=U.prototype.N;U.prototype.getVideoPath=U.prototype.O;U.prototype.getContentType=U.prototype.X;U.prototype.getAdPosition=U.prototype.Q;U.prototype.getTotalDuration=U.prototype.da;U.prototype.getState=U.prototype.M;U.prototype.getCurrentPlayTime=U.prototype.Y;
U.prototype.getBitrate=U.prototype.U;U.prototype.getThumbnailPath=U.prototype.ca;U.prototype.getPlayerType=U.prototype.$;U.prototype.getAutoplayType=U.prototype.T;U.prototype.getViewStartTime=U.prototype.ea;U.prototype.getSections=U.prototype.aa;U.prototype.getAuthors=U.prototype.S;U.verify=function(a){var b=a instanceof HTMLElement&&a.nodeName==="VIDEO",a=a.getAttribute&&a.getAttribute("data-account")!==h;return b&&!a};function V(a){this.a=a;this.B=this.Aa=this.D=j;this.q=t();this.ia()}n=V.prototype;n.ia=function(){this.a.onReady(r(this.la,this));this.a.onTime(r(this.Ld,this));this.a.onComplete(r(this.Md,this))};n.la=function(){this.D=g};n.Ld=function(){this.Aa=j;if(!this.B)this.B=g};n.Md=function(){this.Aa=g};n.P=function(){this.a.getState();return this.D||this.a.getState()!==d};n.N=function(){var a=uc(this);return!a?"":a.title};
function uc(a){if(a.a.getPlaylistIndex===d)return a.a.getPlaylistItem();var b=a.a.getPlaylist();if(!b)return h;var c=b.length,a=a.a.getPlaylistIndex();return c===0||c<=a?h:b[a]}n.O=function(){var a=uc(this);return!a?"":a.mediaid||a.file};n.X=function(){return L};n.Q=m("");n.da=function(){var a=this.a.getDuration();if(a>0)return Math.round(a*1E3)};n.M=function(){if(!this.B)return O;var a=this.a.getState();return this.Aa?"s4":a&&a.toUpperCase()==="PAUSED"?"s3":"s2"};
n.Y=function(){var a=this.a.getPosition();return x(a)};n.U=m(-1);n.ca=function(){var a=uc(this);return!a?"":a.image};n.$=k();n.ea=function(){return isNaN(this.q)?0:ya(this.q)};n.S=k();n.aa=k();n.T=m("unkn");n.ba=m("JW");V.prototype.getStrategyName=V.prototype.ba;V.prototype.isReady=V.prototype.P;V.prototype.getTitle=V.prototype.N;V.prototype.getVideoPath=V.prototype.O;V.prototype.getContentType=V.prototype.X;V.prototype.getAdPosition=V.prototype.Q;V.prototype.getTotalDuration=V.prototype.da;
V.prototype.getState=V.prototype.M;V.prototype.getCurrentPlayTime=V.prototype.Y;V.prototype.getBitrate=V.prototype.U;V.prototype.getThumbnailPath=V.prototype.ca;V.prototype.getPlayerType=V.prototype.$;V.prototype.getViewStartTime=V.prototype.ea;V.prototype.getAuthors=V.prototype.S;V.prototype.getSections=V.prototype.aa;V.prototype.getAutoplayType=V.prototype.T;V.verify=function(a){return v(a.id)&&v(a.registerPlugin)};function W(a){this.a=a;this.Kc="";this.ja=O;this.Ba=L;this.sa="";this.q=t();this.ia()}n=W.prototype;n.ia=function(){this.a.kBind("playerStateChange.cb",r(this.Od,this));this.a.kBind("playerUpdatePlayhead.cb",r(this.Gd,this));this.a.kBind("playerPlayEnd.cb",r(this.Nd,this));this.a.kBind("adStart.cb",r(this.ud,this));this.a.kBind("adEnd.cb",r(this.td,this));this.a.kBind("switchingChangeComplete.cb",r(this.Kd,this))};
n.Od=function(a){switch(a){case "playing":this.ja="s2";break;case "buffering":this.ja="s3";break;case "paused":this.ja="s3"}};n.Gd=function(){this.ja="s2";this.a.kUnbind("playerUpdatePlayhead.cb")};n.Nd=function(){this.ja="s4"};n.ud=function(a){this.Ba="ad";switch(a){case "pre":this.sa="a1";break;case "post":this.sa="a3";break;case "mid":this.sa="a2";break;case "main":this.sa="a5"}};n.td=function(){this.Ba=L};n.Kd=function(a,b){this.Xc=b};
n.P=function(){return this.a.evaluate("{mediaProxy.entry.name}")!=h};n.N=function(){return this.a.evaluate("{mediaProxy.entry.name}")};n.O=function(){if(!this.P())return this.Kc;var a=this.a.evaluate("{mediaProxy.entry.id}");return(this.Kc=a)||""};n.X=l("Ba");n.Q=l("sa");n.da=function(){var a=this.a.evaluate("{duration}");return x(a)};n.M=l("ja");n.Y=function(){var a=this.a.evaluate("{video.player.currentTime}");return x(a)};n.U=l("Xc");
n.ca=function(){return this.a.evaluate("{mediaProxy.entry.thumbnailUrl}")||""};n.$=k();n.T=function(){var a=this.a.evaluate("{configProxy.flashvars.autoPlay}"),b=this.a.evaluate("{configProxy.flashvars.playlistAPI.autoContinue}"),c=this.a.evaluate("{playlistAPI.dataProvider.selectedIndex}");return b&&c>0?"cont":a?"auto":"man"};n.ea=function(){return isNaN(this.q)?0:Fa(this.q)};n.aa=function(){var a=this.a.evaluate("{mediaProxy.entry.tags}");if(a)return a.split(",")};
n.S=function(){var a=this.a.evaluate("{mediaProxy.entry.creatorId}");if(a)return[encodeURIComponent(a)]};n.ba=m("KT");W.prototype.getStrategyName=W.prototype.ba;W.prototype.isReady=W.prototype.P;W.prototype.getTitle=W.prototype.N;W.prototype.getVideoPath=W.prototype.O;W.prototype.getContentType=W.prototype.X;W.prototype.getAdPosition=W.prototype.Q;W.prototype.getTotalDuration=W.prototype.da;W.prototype.getState=W.prototype.M;W.prototype.getCurrentPlayTime=W.prototype.Y;W.prototype.getBitrate=W.prototype.U;
W.prototype.getThumbnailPath=W.prototype.ca;W.prototype.getPlayerType=W.prototype.$;W.prototype.getAutoplayType=W.prototype.T;W.prototype.getViewStartTime=W.prototype.ea;W.prototype.getSections=W.prototype.aa;W.prototype.getAuthors=W.prototype.S;W.verify=function(a){return typeof a.kBind=="function"};function X(a){this.kc=d;this.a=a;this.uc=d;this.D=j;this.Ka=d;this.B=j;this.za=this.Ca=this.q=d;this.kc=p.OO;this.uc=this.a.mb;this.q=t();this.ia()}n=X.prototype;
n.ia=function(){var a=this.uc,b=this.kc.EVENTS;a.subscribe(b.CONTENT_TREE_FETCHED,"OoyalaStrategyPlugin",r(this.la,this));a.subscribe(b.WILL_PLAY_ADS,"OoyalaStrategyPlugin",r(this.wd,this));a.subscribe(b.PLAYING,"OoyalaStrategyPlugin",r(this.ga,this));a.subscribe(b.ADS_PLAYED,"OoyalaStrategyPlugin",r(this.vd,this));a.subscribe(b.METADATA_FETCHED,"OoyalaStrategyPlugin",r(this.Fd,this));a.subscribe(b.EMBED_CODE_CHANGED,"OoyalaStrategyPlugin",r(this.Ad,this))};n.la=function(){this.D=g};
n.wd=function(){var a=this.a.getPlayheadTime(),b=this.a.getDuration();isNaN(a)&&(a=0);this.Ka=a===0?"a1":vc(a,b)?"a3":"a2"};n.ga=function(){this.B=g};n.vd=function(){this.Ka=d};n.Fd=k();n.P=function(){var a=this.a.getState();if(a==="ready"||a==="playing"||a==="paused")this.D=g;return this.D};n.N=function(){var a=this.a.getItem();return a?a.title:""};n.O=function(){return(this.a.getItem()||{}).embedCode||this.a.embedCode||""};n.X=function(){return this.Ka===d?L:"ad"};
n.Q=function(){return this.Ka?this.Ka:""};n.da=function(){var a=this.a.getDuration();return a===-1||isNaN(a)?-1:a*1E3};n.M=function(){if(!this.B)return O;if(this.a.getState()==="paused")return"s3";var a=this.a.getPlayheadTime(),b=this.a.getDuration();return vc(a,b)?"s4":"s2"};function vc(a,b){return a===b||Math.floor(a)===Math.floor(b)||Math.ceil(a)===Math.ceil(b)||Math.ceil(a)===Math.floor(b)||Math.floor(a)===Math.ceil(b)}n.Ad=function(){this.Ka=d};
n.Y=function(){var a=this.a.getPlayheadTime();return a===-1||isNaN(a)?-1:a*1E3};n.U=function(){return this.a.getTargetBitrate()};n.ca=function(){var a=this.a.getItem();return!a?"":a.promo||a.promo_image||a.thumbnail_image};n.$=k();n.T=k();n.ea=function(){return isNaN(this.q)?0:Fa(this.q||0)};n.aa=l("Ca");n.S=l("za");n.ba=m("OO");X.prototype.getStrategyName=X.prototype.ba;X.prototype.isReady=X.prototype.P;X.prototype.getTitle=X.prototype.N;X.prototype.getVideoPath=X.prototype.O;
X.prototype.getContentType=X.prototype.X;X.prototype.getAdPosition=X.prototype.Q;X.prototype.getTotalDuration=X.prototype.da;X.prototype.getState=X.prototype.M;X.prototype.getCurrentPlayTime=X.prototype.Y;X.prototype.getBitrate=X.prototype.U;X.prototype.getThumbnailPath=X.prototype.ca;X.prototype.getPlayerType=X.prototype.$;X.prototype.getAutoplayType=X.prototype.T;X.prototype.getViewStartTime=X.prototype.ea;X.prototype.getSections=X.prototype.aa;X.prototype.getAuthors=X.prototype.S;
X.verify=function(a){return a.hasOwnProperty("mb")&&a.hasOwnProperty("subscribe")&&a.hasOwnProperty("modules")&&a.hasOwnProperty("adPlaying")};function Y(a){this.a=a;this.ha=h;this.Za="";this.ja=O;this.Ba=L;this.sa="";this.q=t();this.a.controller.plugInLoaded&&this.a.controller.plugInLoaded(this)}n=Y.prototype;n.qd=function(a){this.ia(a.controller)};
n.ia=function(a){a.addEventListener("OnLoadRelease",u(this.yc,this));a.addEventListener("OnLoadReleaseUrl",u(this.yc,this));a.addEventListener("OnReleaseStart",u(this.Id,this));a.addEventListener("OnMediaPlay",u(this.Cd,this));a.addEventListener("OnMediaStart",u(this.Ed,this));a.addEventListener("OnMediaPause",u(this.Qb,this));a.addEventListener("OnMediaComplete",u(this.Bd,this));a.addEventListener("OnMediaError",u(this.Qb,this));a.addEventListener("OnMediaBuffer",u(this.Qb,this));a.addEventListener("OnMediaPlaying",
u(this.Dd,this))};n.yc=function(a){if(a.data&&a.data.title)this.ha=a.data;if(a.data&&a.data.guid)this.Za=a.data.guid};n.Id=function(a){s(a.data.clips,function(a){if(a=a.baseClip.guid)return this.Za=a,j});if(this.Za&&a.data.release&&a.data.release.title)this.ha=a.data.release};n.Cd=function(){this.ja="s2"};n.Ed=function(a){this.ja="s2";a=a.data.baseClip;a.isAd?(this.Ba="ad",this.sa=a.isMid?"a2":"a1"):(this.Ba=L,this.sa="")};n.Qb=function(){if(this.ja!=O)this.ja="s3"};n.Bd=function(){this.ja="s4"};
n.Dd=function(a){this.ad=a.currentTime};n.P=function(){return this.ha!=h};n.N=function(){return this.ha.title};n.O=function(){return!this.Za?"":this.Za};n.X=l("Ba");n.Q=l("sa");n.da=function(){return this.ha.duration};n.M=l("ja");n.Y=l("ad");n.U=function(){return this.ha.bitrate};n.ca=function(){return this.ha&&this.ha.defaultThumbnailUrl?this.ha.defaultThumbnailUrl:this.ha.pid?"http://link.theplatform.com/s/ngc/"+this.ha.pid+"?format=poster&height=70&width=95":""};n.$=k();n.T=k();
n.ea=function(){return isNaN(this.q)?0:this.q===d?0:t()-this.q};n.aa=function(){var a=this.ha.keywords?this.ha.keywords.split(","):[],b=[];s(this.ha.categories?this.ha.categories:[],function(a){b.push(encodeURIComponent(a.name))});s(a,function(a){b.push(encodeURIComponent(a.trim()))});return b};n.S=k();n.ba=m("TP");Y.prototype.initialize=Y.prototype.qd;Y.prototype.getStrategyName=Y.prototype.ba;Y.prototype.isReady=Y.prototype.P;Y.prototype.getTitle=Y.prototype.N;Y.prototype.getVideoPath=Y.prototype.O;
Y.prototype.getContentType=Y.prototype.X;Y.prototype.getAdPosition=Y.prototype.Q;Y.prototype.getTotalDuration=Y.prototype.da;Y.prototype.getState=Y.prototype.M;Y.prototype.getCurrentPlayTime=Y.prototype.Y;Y.prototype.getBitrate=Y.prototype.U;Y.prototype.getThumbnailPath=Y.prototype.ca;Y.prototype.getPlayerType=Y.prototype.$;Y.prototype.getAutoplayType=Y.prototype.T;Y.prototype.getViewStartTime=Y.prototype.ea;Y.prototype.getSections=Y.prototype.aa;Y.prototype.getAuthors=Y.prototype.S;
Y.verify=function(a){return typeof a.controller!=="undefined"};function wc(a,b){this.a=a;this.Jc=b;this.Ma=window.location!=window.parent.location;this.Cc=j;this.Vd=t();this.Ic="_v_";this.ua={};I.call(this)}ea(wc,I);var xc=p.QUICK_TEST?1E4:6E4,yc="autoDetect",zc={ae:"title",be:"videopath",$d:"thumbnailpath"},Ac={};n=wc.prototype;
n.G=function(){this.Nb=(this.Sa=this.H.F("_chartbeat3"))?0:1;this.gc=this.Xb=g;this.Fb=j;this.tb=this.Ub=this.mc=this.Ha=d;this.Wa=15E3;this.hb=d;this.Qd=this.cc=this.dc=this.ib=this.jb=0;var a=p.location;this.Vb=j;if(!this.Sa||this.Sa.length===0)this.Sa=la(Hb(this),3);this.H.create("_chartbeat3",this.Sa,2592E3);var b;(b=this.Jc)&&ta(b)?(this.J=new b(this.a),b=g):b=j;if(b){D(this.k,"pingServer","ping.chartbeat.net");D(this.k,"title",document.title);D(this.k,"domain",a.hostname);D(this.k,"path",zb(!!this.k.useCanonical));
this.J.getPlayerType&&D(this.k,"video_type",this.J.getPlayerType());this.mc=setInterval(u(this.Yc,this),1E3);if(this.Ma===g)this.pb=u(this.md,this),w(window,"message",this.pb),this.hb=setInterval(this.Rd,1E3);wc.ma.G.call(this)}};n.Cb=k();
n.ka=function(){if(this.J){if(!Bc(this))this.gc=g;if(!this.gc)return t()-this.Ga>=this.ob&&clearInterval(this.Ha),wc.ma.ka.call(this);if(this.J.isReady())this.Fb=this.gc=j,this.Ub=Cc(this),Dc(this),this.Ha=setInterval(u(this.Eb,this),100),wc.ma.ka.call(this);else if(!this.Fb){this.Fb=g;if(this.Qd++>150)throw"Error: Video strategy never reported its ready state";clearInterval(this.Oa);this.Oa=setInterval(u(this.ka,this),100)}}};
n.Ta=function(){if(this.J){var a=this.k,b=this.J,c=b.getState(),e=Bc(this),f=this.Ma?[]:p._cbq||(p._cbq=[]),i=b.getViewStartTime(),q=Ec(this),B=b.getAutoplayType?b.getAutoplayType():d,i=i===-1?-1:i/1E3,q=q?encodeURIComponent(q):d;if(!Ac.path||Ac.path===e||c==="s2"&&Ac.state!=="s2")switch(Ac={path:e,state:c},f.push(["_vi",va(Fc(this))]),f.push(["_vp",e]),f.push(["_vdd",encodeURIComponent("video@"+(a.videodomain||a.domain))]),f.push(["_vs",b.getState()]),b.getContentType&&f.push(["_vt",b.getContentType()]),
b.getAdPosition&&f.push(["_vap",b.getAdPosition()]),f.push(["_vtn",va(Ec(this))]),f.push(["_vd",b.getTotalDuration()]),b.getState()){case O:case "s2":case "s3":f.push(["R","1"]);break;case "s4":f.push(["R","0"])}a=Gc(this)+Z("_vt",b.getContentType?b.getContentType():"")+Z("_vap",b.getAdPosition?b.getAdPosition():"")+Z("_vs",c)+Z("_vbr",b.getBitrate?b.getBitrate():"")+Z("_vvs",i)+Z("_vpt",b.getCurrentPlayTime())+Z("_vtn",q)+Z("_vaup",B||"unkn")+Z("_vplt",a.video_type)+Z("_vce",this.cc)+Z("c",Math.round(ya(this.Vd)/
600)/100)+"&W=0&R="+(c==="s2"?"1":"0")+"&I="+(c!=="s2"?"1":"0")+"&E="+this.dc+"&j="+(this.Wa/1E3+15)+Hc(this)+"&tz="+(new Date).getTimezoneOffset()+(yb(this.H)?"&l=1":"")+"&_";this.Ma===g&&s(f,function(a){window.top.postMessage("cbqpush::"+a.join("::"),"*")});this.eb(a)}};function Z(a,b){return b!==d&&b!==""?"&"+a+"="+b:""}n.bb=function(){this.H.update("_cb_cp",this.Da,3600,j,",")};function Hc(a){var b=a.H.F("_cb_cp");a.H.remove("_cb_cp");return b?"&D="+b:""}
function Ic(a){return a.k.subdomain?a.k.subdomain:oa(p.location.hostname)}function Bc(a){var b=a.ua.videopath;if(b)return b;if(a.k.videoPathHash){if(a=Fc(a))return la(a)}else return a.J.getVideoPath();return""}function Fc(a){return a.ua.title||a.J.getTitle()}function Ec(a){return a.ua.thumbnailpath||a.J.getThumbnailPath()}
function Gc(a){var b=a.k,c=a.J,e=p.location,f=c.getUid&&c.getUid()||b.uid,i=b.videodomain||c.getHost&&c.getHost()||b.domain,i=encodeURIComponent("video@"+i),q="",B=a.cb?"&b="+a.cb:"",o,C=a.k.path;o=a.k.useSubDomains!==j&&C&&C.substr(0,1)==="/"?Ic(a)+C:C;var C=c.getSections&&c.getSections(),M=c.getAuthors&&c.getAuthors(),P=b.sections?"&g0="+encodeURIComponent(b.sections):"",S=b.authors?"&g1="+encodeURIComponent(b.authors):"",C=C===d||b.videoPageGroups?P:"&g0="+C.join(","),M=M===d||b.videoPageGroups?
S:"&g1="+M.join(","),S="",P=Bc(a);if(a.tb===d)a.tb=P;else if(P!=a.tb)S=Z("D",a.Da),a.Da=la(Hb(a)),a.tb=P,a.jb=0,a.ib=0,a.dc=0,a.cc=0,a.Xb=g;if(a.Xb||S){if(a.Ma===j||a.Ma===g&&a.Cc===g)a.Xb=j;q=(Mb(a)?"&v=":"&r=")+Nb(a)}a.dc+=a.jb;a.jb=0;a.cc+=a.ib;a.ib=0;Dc(a);var fa=P="",ba="",N="",E="",ra="",ia="",ja="";if(!a.Ma===g||a.Vb===g)P="&_vi="+Ob(a),fa="&_vp="+encodeURIComponent(o),ba="&_vh="+va(Ic(a)),N="&_vdd="+encodeURIComponent(b.domain),a.Vb===g?(E=b.u,ra=b.t,ia=Ma(b.v),ja=Ma(b.r)):(E=J("u"),ra=J("t"),
ia=Ma(J("v")),ja=Ma(J("r")));o="";o=sa(ia)?"&_pv="+ia:sa(ja)?"&_pr="+ja:"&_pr=NA";ia="&_pu=";ja="&_pt=";ia+=E?E:"NA";ja+=ra?ra:"NA";E=!b.noCookies&&a.H.isSupported();ra=c.getStrategyName?c.getStrategyName():"";return(e.protocol||"http:")+"//"+b.pingServer+"/ping?h="+i+"&g="+f+"&p="+va(Bc(a))+"&i="+Fc(a)+C+M+"&u="+a.Sa+"&t="+a.Da+"&x=0&y=0&V=69"+Z("VS",ra)+(E?"&n="+a.Nb:"&nc=1")+B+q+S+Z("_vd",c.getTotalDuration())+P+fa+ba+ia+ja+o+N}n.Eb=function(){var a=Cc(this);if(this.Ub!=a)this.Ub=a,Dc(this),this.ka()};
function Dc(a){var b=a.Wa;a.Wa=(a.J.getState()==="s2"||Jc(a))===g?5E3:a.J.getState()===O?xc:15E3;if(b!=a.Wa)b=a.Wa,clearInterval(a.Oa),a.Oa=setInterval(u(a.ka,a),b)}function Cc(a){return a.J.getState()+a.J.getAdPosition()}function Jc(a){return a.J.getAdPosition()!==""&&a.J.getAdPosition()!==d&&a.J.getViewAdPlayTime!==-1&&a.J.getViewAdPlayTime!==d}n.Yc=function(){if((this.J.getState()==="s2"||Jc(this))===g)this.jb+=1,this.J.getContentType()===L&&(this.ib+=1)};
n.Rd=function(){window.parent.postMessage("cbdata?","*")};n.md=function(a){if(a.source===window.parent&&(a=a.data,sa(a)&&a.indexOf("domain=")===0)){this.Vb=g;var b={domain:g,uid:g,path:g,title:g,referrer:g,internal:g,subdomain:g,token:g,u:g,t:g,v:g,r:g},c=this;s(a.split("&"),function(a){var a=a.split("="),f=a[0],a=a[1];b[f]&&(c.k[f]=decodeURIComponent(a))});pa(window,"message",this.pb);clearInterval(this.hb);this.hb=d;this.Cc=g;this.ka()}};
n.setProperty=function(a,b){var c=j,e=this;s(zc,function(f){if(a.toLowerCase()==f)return e.ua[f]=b,c=g,j});return c};n.terminate=function(){clearInterval(this.mc);clearInterval(this.hb);clearInterval(this.Ha);pa(window,"message",this.pb);wc.ma.terminate.call(this)};n.xa=function(){wc.ma.xa.call(this);this.Jc=this.a=this.pb=h};function $(a){this.a=a;this.D=g;this.B=j;this.q=t();this.Ha=this.za=this.Ca=d;this.Lc=p._sf_async_config.ytApikey;this.Va=d;Kc(this,Lc(this));this.ia()}n=$.prototype;n.ia=function(){this.Ha=setInterval(r(this.Eb,this),100);var a=this.a.getPlayerState();(a===1||a===2||a===0)&&this.ga()};n.Eb=function(){if(this.a.getPlayerState()===1)clearInterval(this.Ha),this.Ha=d,this.ga()};n.la=function(){this.D=g};n.ga=function(){if(!this.B)this.B=g};
function Lc(a){var b;return(b=(a=a.a.getVideoUrl())&&a.match(/[?&]v=([^&]+)/),a=b)&&a[1]}function Kc(a,b){var c="https://www.googleapis.com/youtube/v3/videos?part=snippet&id="+b+"&key="+a.Lc,e=u(function(){this.Va={id:b,title:""}},a);if(a.Lc){var f=u(function(a){if(b==Lc(this))a?a.error?e():this.Va={id:b,title:a&&a.items&&a.items[0]&&a.items[0].snippet&&a.items[0].snippet.title||""}:e()},a);za(c,f)}else e()}n.P=function(){return this.D&&!!this.Va};
n.N=function(){return this.Va&&this.Va.id===Lc(this)?this.Va.title:""};n.O=function(){return Lc(this)||this.a.getVideoUrl()};n.X=function(){return L};n.Q=m("");n.da=function(){var a=this.a.getDuration();return qa(a)?a*1E3:a};n.M=function(){if(!this.B)return O;var a=this.a.getPlayerState();return a===0?"s4":a===2?"s3":"s2"};n.Y=function(){var a=this.a.getCurrentTime();return x(a)};n.U=m(-1);n.ca=function(){return"http://img.youtube.com/vi/"+Lc(this)+"/default.jpg"};n.$=k();n.T=k();
n.ea=function(){return isNaN(this.q)?0:ya(this.q)};n.aa=l("Ca");n.S=l("za");n.ba=m("YT");$.prototype.getStrategyName=$.prototype.ba;$.prototype.isReady=$.prototype.P;$.prototype.getTitle=$.prototype.N;$.prototype.getVideoPath=$.prototype.O;$.prototype.getContentType=$.prototype.X;$.prototype.getAdPosition=$.prototype.Q;$.prototype.getTotalDuration=$.prototype.da;$.prototype.getState=$.prototype.M;$.prototype.getCurrentPlayTime=$.prototype.Y;$.prototype.getBitrate=$.prototype.U;
$.prototype.getThumbnailPath=$.prototype.ca;$.prototype.getPlayerType=$.prototype.$;$.prototype.getAutoplayType=$.prototype.T;$.prototype.getViewStartTime=$.prototype.ea;$.prototype.getSections=$.prototype.aa;$.prototype.getAuthors=$.prototype.S;$.verify=function(a){return ta(a.getDuration)&&ta(a.getVideoUrl)&&ta(a.getVideoEmbedCode)};function Mc(){p._cbv_strategies||(p._cbv_strategies=[]);p._cbv_strategies.push(X);p._cbv_strategies.push(U);p._cbv_strategies.push(T);p._cbv_strategies.push($);p._cbv_strategies.push(V);p._cbv_strategies.push(R);p._cbv_strategies.push(Q);p._cbv_strategies.push(W);p._cbv_strategies.push(Y);this.ec=[];this.ua=[];this.k=p._sf_async_config||{};sb("_cbv",u(this.nd,this));this.k[yc]!==j&&Nc()}
Mc.prototype.nd=function(a){if(aa(a)=="array"&&typeof a[0]=="string"){var b=a[0];if(b==="autoDetectYouTubeIframes"){Oc();return}else if(b==="removePlayer"){Pc(this,a[1]);return}else if(b==="setProps"){Qc(a[1])||this.ua.push(a[1]);return}}Rc(this,a)};function Rc(a,b){var c=j,e=p._cbv_strategies;v(window.jwplayer)&&(b=ta(b)?b():b);s(e,function(a){if(a.verify(b)===g)return c=a,j});c===j||Sc(a,b,c)}
function Pc(a,b){var c=a.ec,e=p.pSUPERFLY_video,f=wa(c,function(a){return b===a});f!==-1&&c.splice(f,1);f=wa(e,function(a){return a.a===b});f!==-1&&e.splice(f,1)[0].xa()}function Qc(a){if(!v(a))return j;var b=a.player,c=xa(function(a){return a.a===b});return!v(c)?j:Tc(c,a)}function Tc(a,b){var c=j;s(b,function(b,f){if(f!=="player"&&(c=a.setProperty(f,b),!c))return c});return c}
function Sc(a,b,c){var e=j;s(a.ec,function(a){if(b===a)return e=g,j});if(!e){c=new wc(b,c);p.pSUPERFLY_video.push(c);for(var f=a.ua.length-1;f>-1;f--)Tc(c,a.ua[f])&&a.ua.splice(f,1);Kb(c);a.ec.push(b)}}
function Nc(){if(ta(window.jwplayer)&&v(window.jwplayer()))for(var a=0,b=window.jwplayer(a);v(b.id);)window._cbv.push(b),b=window.jwplayer(++a);else window.flowplayer?window._cbv.push(window.flowplayer):window.brightcove&&window.experienceJSON?window._cbv.push(window.brightcove):window.videojs?(a=window.videojs.plugin,ta(a)&&a("chartbeat",function(a){this.cb_configs=a;window._cbv.push(this)})):window.kWidget?window.kWidget.addReadyCallback(function(a){window._cbv.push(document.getElementById(a))}):
window.$pdk?window._cbv.push(window.$pdk):s(document.getElementsByTagName("video"),function(a){window._cbv.push(a)})}function Oc(){function a(){function a(b){p._cbv.push(b.target)}var b=p.YT.Player;s(document.getElementsByTagName("iframe"),function(f){var i=f.src,q=i&&i.indexOf("www.youtube.com/embed/");i&&q>=0&&q<9&&new b(f,{events:{onReady:a}})})}if(p.YT&&p.YT.Player)a();else{var b=p.onYouTubeIframeAPIReady;p.onYouTubeIframeAPIReady=function(){if(b){try{b.apply(p,arguments)}catch(c){}a()}}}};if(window.location==window.parent.location&&!p.pSUPERFLY){var Uc=new nc,Vc={};p.pSUPERFLY=Vc;var Wc=!!fc;Vc.virtualPage=function(a,b){if(!cb){var c=p._sf_async_config;c.virtualReferrer=p.location.protocol+"//"+c.domain+c.path;c.path=Bb(a);b&&(c.title=b);Uc.kb();Wc&&fc.evps();Uc.Hc();Wc&&fc.svps()}};Vc.activity=u(Uc.Rc,Uc);Kb(Uc);var Xc=G.Z(g);if(Xc)if(Xc.getItem("_cb_ip")){var Yc=p.location;(!/^(.+[.])?chartbeat\.com$/.test(Yc.hostname)?0:/^\/publishing\/(overlay|hud|mab)\//.test(Yc.pathname))||lc()}else w(p,
"message",mc)}p.pSUPERFLY_video||(p.pSUPERFLY_video=[]);new Mc;})();
